/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Simonetta', 'Georgia', 'Cambria', 'serif'],
      },
      fontSize: {
        'caption2': ['clamp(11px, 10.4px + 0.08vw, 12px)', '16px'],
        'caption1': ['clamp(13px, 12.2px + 0.1vw, 14px)', '18px'],
        'body1': ['clamp(15px, 14px + 0.16vw, 17px)', '22px'],
        'subtitle2': ['clamp(17px, 15.8px + 0.18vw, 19px)', '24px'],
        'subtitle1': ['clamp(22px, 20.6px + 0.22vw, 25px)', '28px'],
        'title3': ['clamp(26px, 24.5px + 0.28vw, 30px)', '34px'],
      },
      colors: {
        t: {
          fg1: 'var(--t-fg1)',
          fg2: 'var(--t-fg2)',
          fg3: 'var(--t-fg3)',
          fg4: 'var(--t-fg4)',
          'fg-disabled': 'var(--t-fg-disabled)',
          'fg-brand': 'var(--t-fg-brand)',
          'fg-brand-hover': 'var(--t-fg-brand-hover)',
          bg1: 'var(--t-bg1)',
          'bg1-hover': 'var(--t-bg1-hover)',
          'bg1-selected': 'var(--t-bg1-selected)',
          bg2: 'var(--t-bg2)',
          bg3: 'var(--t-bg3)',
          bg4: 'var(--t-bg4)',
          bg5: 'var(--t-bg5)',
          'bg-brand': 'var(--t-bg-brand)',
          'bg-brand-hover': 'var(--t-bg-brand-hover)',
          'bg-brand-selected': 'var(--t-bg-brand-selected)',
          'bg-static': 'var(--t-bg-static)',
          'bg-subtle-hover': 'var(--t-bg-subtle-hover)',
          'bg-subtle-selected': 'var(--t-bg-subtle-selected)',
          stroke1: 'var(--t-stroke1)',
          stroke2: 'var(--t-stroke2)',
          stroke3: 'var(--t-stroke3)',
          'stroke-brand': 'var(--t-stroke-brand)',
          'brand-10': 'var(--t-brand-10)',
          'brand-40': 'var(--t-brand-40)',
          'brand-60': 'var(--t-brand-60)',
          'brand-70': 'var(--t-brand-70)',
          'brand-80': 'var(--t-brand-80)',
          'brand-90': 'var(--t-brand-90)',
          'brand-100': 'var(--t-brand-100)',
          'brand-120': 'var(--t-brand-120)',
          'brand-140': 'var(--t-brand-140)',
          'brand-160': 'var(--t-brand-160)',
          success: 'var(--t-success)',
          warning: 'var(--t-warning)',
          danger: 'var(--t-danger)',
          'danger-bg': 'var(--t-danger-bg)',
          'success-bg': 'var(--t-success-bg)',
          'warning-bg': 'var(--t-warning-bg)',
        },
      },
      spacing: {
        'rail': '76px',
        'panel': '320px',
        'header': '48px',
      },
      borderRadius: {
        'fluent': '6px',
        'fluent-lg': '12px',
      },
      boxShadow: {
        'teams-card': '0 1px 4px rgba(0,0,0,0.08)',
        'teams-dropdown': '0 4px 16px rgba(0,0,0,0.12)',
      },
    },
  },
  plugins: [],
};
